application: twittus
version: 1
runtime: python
api_version: 1

handlers:
- url: /off
  script: broadcast.py
  login: admin
- url: /on
  script: broadcast.py
  login: admin
- url: /broadcast/realtime
  script: broadcast.py
  login: admin
- url: /
  script: broadcast.py

